name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build/Push Rails Base
        uses: docker/build-push-action@v6
        with:
          context: ./rails
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: cayt3r/rails

      - name: Build/Push Rails Build
        uses: docker/build-push-action@v6
        with:
          context: ./rails-build
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: cayt3r/rails-build

      - name: Build/Push Go Base
        uses: docker/build-push-action@v6
        with:
          context: ./go
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: cayt3r/go

      - name: Build/Push Go Build
        uses: docker/build-push-action@v6
        with:
          context: ./go-build
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: cayt3r/go-build
